Hotfix = require("Hotfix/Hotfix")
Hotfix:init()
require("Global/CSDefine")
require("Common/Class")
require("Common/LuaUtil")
require("Common/MathExt")
require("Common/TableExt")
require("Common/StringExt")
CsGameManagerUtil = CS.miHoYo.GameManager.instance
Logger = require("Debug/Logger")
Config = require("Global/Config")
XLuaSystem = require("Common/XLuaSystem")
SingletonUtil = require("UIFramework/SingletonUtil")
LocalDataUtil = require("Common/LocalDataUtil")
require("UIFramework/Base/UIBase")
require("UIFramework/Base/UIPanel")
require("UIFramework/Base/UIWindow")
UIUtil = require("UIFramework/UIUtil")
EntityUtil = require("UIFramework/EntityUtil")
TagUtil = require("UIFramework/TagUtil")
ColorUtil = require("UIFramework/ColorUtil")
UIManagerInstance = G.New(require("UIFramework/UIManager"))
RTManagerInstance = G.New(require("RT/RTManager"))
ModelPreviewManagerIns = G.New(require("ModelPreview/ModelPreviewManager"))
NpcPreviewManagerIns = G.New(require("ModelPreview/NpcPreviewManager"))
NetHandlerIns = G.New(require("Net/NetHandler"))
InputAction = require("Input/InputAction")
ActionType = require("Input/InputActionType")
InputManagerIns = G.New(require("Input/InputManager"))
JoystickUICtrl = require("Input/JoystickUICtrl")
LocManagerIns = G.New(require("Localization/LocalizationManager"))
LocType = require("Localization/LocalizationType")
AudioManagerIns = G.New(require("Audio/AudioManager"))
WType = require("Audio/WwiseTypeGuid")
CoolDownManagerIns = G.New(require("CoolDown/CoolDownManager"))
BubbleManagerIns = G.New(require("UI/Bubble/BubbleManager"))
LuaTimeUtil = require("Common/LuaTimeUtil")
RedPointUtil = require("RedPoint/RedPointUtil")
BGSceneManagerIns = require("BGScene/BGSceneManager")
UIIdleDetectManagerIns = G.New(require("UIIdleDetect/UIIdleDetectManager"))
UINavigatorIns = G.New(require("Global/UINavigator"))
PlayerControlInputPanelBase = require("UI/PlayerCtrl/Base/PlayerControlInputPanelBase")
PlayerControlInputElementBase = require("UI/PlayerCtrl/Base/PlayerControlInputElementBase")
KeyMouseInputPanel = require("UI/PlayerCtrl/KeyMouse/KeyMouseInputPanel")
LoadingPanelBase = require("UI/Loading/LoadingPanelBase")
TutorialPanelBase = require("UI/Tutorial/Base/TutorialPanelBase")
GraphicalTutorialPanel = require("UI/Tutorial/GraphicalTutorial/GraphicalTutorialPanel")
StarPanelBase = require("UI/CompanionStarDetail/Base/StarPanelBase")
BuriedPointReportActionEnum = require("BuriedPointReport/BuriedPointReportActionEnum")
EntityTagTags = require("Gen/EntityTagTags")
StateTags = require("Gen/StateTags")
EventIDTags = require("Gen/EventIDTags")
SceneTags = require("Gen/SceneTags")
TutorialUIKey = require("Tutorial/TutorialUIKey")
TutorialTrackingPoint = require("Tutorial/TutorialTrackingPoint")
ATLTagTags = require("Gen/ATLTagTags")
DetailPanelComponentBase = require("UI/Codex/DetailPage/Component/Base/DetailPanelComponentBase")
ComplexCodexInfoPanelBase = require("UI/Codex/ComplexDetailPage/Base/ComplexCodexInfoPanelBase")
